### ISSUE TITLE
Asshole tshirt doesnt work

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#48]
![207185086-a3451619-09a1-45ad-9b55-eb6d52dcc9d2](https://user-images.githubusercontent.com/101466850/207274859-9a166461-11d4-4415-bd79-7535cd11facc.png)
i am sry but i used this option and it didnt work. for asshole t-shirt
can not see t-shirt i tried it in 5 different session only solo
https://user-images.githubusercontent.com/101466850/207275097-5aef1af6-a8c9-49f8-bf53-64699383270a.mp4

**Comment by jhowkNx** [comment]
I just checked on a clean account and see how it still works. Remember that if you already have more than 123 exclusive items, and try to get some new one, possibly it will not be added to you because of this clothing limitation.
If you go to your closet in your apartment you might still see that item there.

![image](https://user-images.githubusercontent.com/79918850/207591853-ada91152-bdcd-4b14-9cd6-ea08fd7fa936.png)
